name: Deploy Website

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Files
        run: |
          # Replace the destination directory with your actual directory
          cp -r ./* /var/www/html/
