version: '3'
services:
  web:
    image: nginx:latest  # Replace with the appropriate web server image if not using Nginx
    ports:
      - "80:80"
    volumes:
      - ./your-website-folder:/usr/share/nginx/html  # Mount your website files into the container
      
